# Custom Resource Definitions from the kubernetes-aws-resource-service
#
# These should be synced with kubernetes-aws-resource-service/resources.yml
#
# FIXME: The operator should apply these automatically (see https://github.com/Collaborne/kubernetes-aws-resource-service/issues/9)
# XXX: `spec.version` is deprecated in 1.13 (for the versions array), but required in 1.10
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: queues.aws.k8s.collaborne.com
spec:
  group: aws.k8s.collaborne.com
  scope: Namespaced
  names:
    kind: Queue
    plural: queues
  version: v1
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: roles.aws.k8s.collaborne.com
spec:
  group: aws.k8s.collaborne.com
  scope: Namespaced
  names:
    kind: Role
    plural: roles
  version: v1
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: buckets.aws.k8s.collaborne.com
spec:
  group: aws.k8s.collaborne.com
  scope: Namespaced
  names:
    kind: Bucket
    plural: buckets
  version: v1
---
